baseurl                  = "https://andrewcolabella.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "andrew colabella"
author = "Andrew Colabella"
theme                    = "tokiwa"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = ""
    homepage             = ""                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = ""               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "andrew colabella"
    # rss                = ""

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "AR"
    url = "/ar/"
    weight = 1
  [[menu.main]]
    name = "stories"
    url = "/stories/"
    weight = 2
  [[menu.main]]
    name = "photos"
    url = "/photos/"
    weight = 3

[social]
instagram="http://example.com/"
youtube="http://youtube.com/"
github="http://github.com/"
